### PR TITLE
#67 fix url case sensitivity

### LINKED ISSUE #67: Form Builder Validator URLs: Make url validator case insensitive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

^9.0.0-dev.1

### Platforms

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Web
- [ ] Windows

### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 3.13.8, on macOS 13.5 22G74 darwin-arm64, locale en-KE)
  [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
  [!] Xcode - develop for iOS and macOS (Xcode 15.0.1)
      ✗ Unable to get list of installed Simulator runtimes.
  [✓] Chrome - develop for the web
  [!] Android Studio (version unknown)
      ✗ Unable to determine Android Studio version.
  [✓] Android Studio (version 2022.1)
  [✓] VS Code (version 1.71.2)
  [✓] Connected device (2 available)
      ! Error: Browsing on the local area network for Mboya’s iPhone. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
  [✓] Network resources
```

</details>

### Minimal code example

<details>
  <summary>Code sample</summary>

```dart
  /// Inside a formbuildertextfield
  validator: FormBuilderValidators.compose([
   FormBuilderValidators.url()
  ]),
```

</details>

### Current Behavior

Upon entering a capital letter on the top level domain, the validator fails showing that the URL is invalid. 
For example: 
HTTPS://WWW.GOOGLE.COM - invalid link
https://www.google.com - valid link
https://WWW.GOOGLE.com - valid link
HTTPS://WWW.GOOGLE.COM - invalid link

### Expected Behavior

I believe the URL should be case insensitive. Any part of it having a capital letter should not invalidate the URL
While this is my exact case I'm not sure if it's valid for everyone. If given the go-ahead I could modify the REGEX pattern to include capital letters for the top level domain.

### Steps To Reproduce

1. Create a formbuildertextfield
2. add a formbuildervalidators.url as the textfield's validator
3. Run the project and try to type a url with a capital letter for the top level domain e.g. https://google.Com instead of https://google.com

### Aditional information

_No response_

### PR DESCRIPTION
**Pull request by bjarn-hau**
## Connection with issue(s)

Close #67

## Solution description

I added a `toLowercase` call for the split string before protocol check and before hostname check.

## Screenshots or Videos
_test should be enough_

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [x] Add unit test to verify new or fixed behaviour
- [x] If apply, add documentation to code properties and package readme

### CODE REVIEW

File: test/form_builder_validators_test.dart [hunk 1]
```diff
@@ -412,6 +412,11 @@ void main() {
             expect(validator('www.google.com'), isNull);
             expect(validator('google.com'), isNull);
             expect(validator('http://google.com'), isNull);
+            expect(validator('HTTPS://GOOGLE.COM'), isNull);
```
Comment (bjarn-hau) [inline test/form_builder_validators_test.dart:415]: If you got some more test cases please let me know.

File: lib/src/utils/validators.dart [hunk 2]
```diff
@@ -32,7 +34,7 @@ bool isURL(String? str,
     List<String> hostBlacklist = const []}) {
   if (str == null ||
       str.isEmpty ||
-      str.length > 2083 ||
+      str.length > _maxUrlLength ||
```
Comment (bjarn-hau) [inline lib/src/utils/validators.dart:37]: I added this because I actually didn't know that 2083 was the maximum length for an url

**Review by deandreamatias — APPROVED** [review]
